/**
 * `@zelinqa/nbq` — official TypeScript SDK for the NBQ Engine V1 API.
 *
 * Two independent clients, one key each, least privilege:
 * - `NBQClient` drives conversations (scope `runtime`);
 * - `NBQConfigurationClient` reads and publishes the question bank
 *   (scopes `configuration:read` / `configuration:write` / `configuration:publish`).
 *
 * Backend only. An NBQ key is a bearer credential: never ship it to a browser or
 * a mobile bundle.
 */
export {
  DEFAULT_COMPILATION_TIMEOUT_MS,
  DEFAULT_POLL_INTERVAL_MS,
  NBQConfigurationClient,
} from "./configuration.js";
export {
  apiErrorFromResponse,
  GATEWAY_FORBIDDEN_MESSAGE,
  NBQAPIError,
  type NBQAPIErrorOptions,
  NBQAuthenticationError,
  NBQCompilationInProgressError,
  NBQCompilationTimeoutError,
  NBQCompiledArtifactUnavailableError,
  NBQConfigurationValidationError,
  NBQConflictError,
  NBQConnectionError,
  NBQConstraintNoMatchError,
  NBQError,
  NBQIdempotencyContentionError,
  NBQIdempotencyKeyReusedError,
  NBQInsufficientScopeError,
  NBQInvalidChoiceError,
  NBQInvalidPreviousTurnError,
  NBQNotFoundError,
  NBQRateLimitError,
  NBQServerError,
  NBQStateVersionConflictError,
  NBQUnknownCompilationError,
  NBQUnknownConfigurationError,
  NBQUnknownSessionError,
  NBQValidationError,
} from "./errors.js";
export {
  DEFAULT_BASE_URL,
  DEFAULT_MAX_RETRIES,
  DEFAULT_TIMEOUT_MS,
  USER_AGENT,
} from "./http.js";
export {
  NBQClient,
  Session,
  type SessionEventsInput,
  type SessionNextInput,
} from "./runtime.js";
export type {
  Candidate,
  CandidateChoice,
  ClientUpdates,
  CompilationError,
  CompilationStatus,
  CompletionRole,
  Configuration,
  ConfigurationAuditActor,
  ConfigurationAuditDiff,
  ConfigurationAuditEvent,
  ConfigurationAuditPage,
  ConfigurationAuditResource,
  ConfigurationAuditResourceType,
  ConfigurationChange,
  ConfigurationChangesRequest,
  ConfigurationChangesResponse,
  ConfigurationIssue,
  ConfigurationResponse,
  ConfigurationState,
  ConfiguredChoice,
  ConfiguredQuestion,
  ContextUpdate,
  ConversationMessage,
  ConversationMessageDelta,
  ConversationSummary,
  DataClientUpdate,
  ErrorCode,
  ErrorEnvelope,
  FeedbackRequest,
  FeedbackResponse,
  Fetch,
  GetConfigurationQuery,
  InitialHistoryItem,
  ListAuditQuery,
  ListQuestionsQuery,
  NBQClientOptions,
  NextRequest,
  NextResponse,
  NotApplicableDataUpdate,
  Objective,
  ObjectiveChange,
  ObjectiveClientOverrideView,
  ObjectiveOverrideUpdate,
  ObjectiveOverrideValue,
  ObjectiveProgress,
  PendingDecisionView,
  PreviousTurn,
  ProgressStatus,
  ProgressView,
  PublicQuestionState,
  PublicTargetState,
  PublishRequest,
  QualificationLevel,
  QuestionChange,
  QuestionListResponse,
  QuestionOutcome,
  QuestionOutcomeRecord,
  QuestionType,
  RequestOptions,
  SelectionOptions,
  SelectionWarning,
  SessionCreateRequest,
  SessionEventsRequest,
  SessionState,
  SessionStateResponse,
  SetDataUpdate,
  StopReason,
  StructuredAnswer,
  SubObjective,
  SubObjectiveChange,
  SubObjectiveClientOverrideView,
  SubObjectiveOverrideUpdate,
  SubObjectiveOverrideValue,
  SubObjectiveProgress,
  SubObjectiveSelection,
  SuccessInformation,
  SuccessInformationChange,
  UnsetDataUpdate,
  VersionInfo,
  WaitForCompilationOptions,
} from "./types.js";
export { VERSION } from "./version.js";
